### ISSUE TITLE
Scrolling the page while dragging

### ISSUE THREAD

**Issue by RaphiStein** [fatlinesofcode/ngDraggable#71]
Sometimes the drop zone is further down the page and requires being scrolled to. When dragging something from the top region of the page, it's impossible to scroll while dragging unless you have a scroll wheel. 

Anyone have suggestions on how we can add the ability to get the page to scroll when dragging the object to the bottom?

**Comment by jfspencer** [comment]
I have a pull request to address this issue. The pull contains a new CSS class drag-in-progress which is applied to ngDrop elements during a drag. This CCS class can be coupled the the added ng-on-hover which defines an event handler when the dragged object is hovering over a ngDrop region. I have an example code pen here http://codepen.io/jfspencer/full/jEPGGm
It is applied to ionicSlideBoxes, but could be easily adapted to to call a scroll function with an interval or something like that.

**Comment by jfspencer** [comment]
The pull request is #67

**Comment by pitymaia** [comment]
Hi, great work with ngDraggable!
This pull request has a great feature to make the page scroll when dragging, with is a very important behaviour. For now i made a fork and a merge of the most actual code and this pull request #67, but is not good merge other people code that i don't really understand... so, there is any prevision when this go to your master branch? Just for me plan better my project...

**Comment by Gunbit** [comment]
Hi,
is this the solution for the scrolling page?
i need a solution to scroll vertical with ngDraggable.

Thanks

**Comment by JamesBrauman** [comment]
I needed this functionality so I implemented it in this PR #86 let me know what you think.

**Comment by fatlinesofcode** [comment]
PR merged. Example implementation anyone?

**Comment by Bhupesh82** [comment]
I think issue remained the same.. please advise any solution or any working example.
